
version: "2"
services:
  django:
    image: blitzagency/python-web:3
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    stdin_open: true
    working_dir: /usr/app/django
    tty: true
    command: "/bin/bash"
    links:
      - postgres:postgres
    environment:
      DJANGO_SETTINGS_MODULE: app.config.settings.local
      PYTHONPATH: /usr/app/django/project:/usr/app/django/project/vendor
      DEBUG: "true"
    logging:
      driver: none

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - /usr/lib/postgresql
      - .:/usr/app/django
    environment:
     POSTGRES_USER: vagrant
     POSTGRES_PASSWORD: vagrant
    logging:
      driver: none

  heroku:
    image: dinopetrone/heroku:latest
    working_dir: /usr/app/django
    command: "/bin/bash"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/app
    links:
      - postgres:postgres
    environment:
      DJANGO_SETTINGS_MODULE: app.config.settings.prod
      PYTHONPATH: /usr/app/django/project:/usr/app/django/project/vendor
      DEBUG: "true"
    logging:
      driver: none

